### ISSUE TITLE
Nombre Sistema

### ISSUE THREAD

**Issue by aitrusgit** [alejandro11k/rentauto#1]
Sistema me hace pensar en un god-object que hace todo todo todisimo. Lo que ustedes hicieron es un servicio para manejar operaciones relativas a los usuarios. En el TP van a aparecer otros servicios. Llamenlo UsuarioService, ServicioDeUsuario, FacadaUsuarios... como quieran.

**Comment by aitrusgit** [comment]
Amen del nombre, está muy bien la implementación

**Comment by alejandro11k** [comment]
renombrado Sistema a ServicioUsuario
