### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by aitrusgit** [alejandro11k/rentauto#2]
Es una buena práctica que empecemos a trabajar con javadocs para documentar el contrato de las clases que creamos. En algunos métodos de sus servicios vi que escribieron documentación, simplemente es cuestión de escribirla de otra forma. Solo una cuestión de estandarización.

Algo así sería mejor:
![image](https://cloud.githubusercontent.com/assets/819334/9788954/54cf50b8-57a3-11e5-9d45-f22010f5fa6e.png)

**Comment by aitrusgit** [comment]
(Vean solo el javadoc, el screenshot lo saqué de otro TP)

**Comment by aitrusgit** [comment]
Es algo cosmético solo dentro del alcance del TP. En la vida real es una práctica casi innegociable.

**Comment by alejandro11k** [comment]
Utilizacion de javadoc en la clase ServicioUsuario a modo de ejemplo/practica
