### ISSUE TITLE
HomeBBDD.actualizar

### ISSUE THREAD

**Issue by aitrusgit** [alejandro11k/rentauto#3]
No está bien que para actualizar hagan algo así:

``` xtend
override actualizar(Usuario usuario) {
   borrarUsuario(usuario)
   agregarUsuario(usuario)
}
```

En este TP no se nota el problema, pero en cuanto tengan alguna otra entidad que referencie a un Usuario (tabla con fk a usuarios) no van a poder borrar usuarios sin que haya un problema de constraints.

La alternativa mas rápida y segura es el UPDATE

**Comment by aitrusgit** [comment]
Lo que si, ojo con repetir código entre actualizar / insertar.

**Comment by alejandro11k** [comment]
corregido!
