### ISSUE TITLE
Mapeo de Reservas

### ISSUE THREAD

**Issue by aitrusgit** [alejandro11k/rentauto#6]
Ustedes tienen en Auto.hbml.xml

``` xtend
        <bag name="reservas" cascade="save-update" inverse="true">
            <key column="auto" />
            <one-to-many class="ar.edu.unq.epers.model.Reserva" />
        </bag>
```

Y en Reserva.hbm.xml

``` xtend
        <many-to-one class="ar.edu.unq.epers.model.Auto" 
            name="auto" column="patente" />
```

Fijense que es la misma relacion (dos extremos de la misma) pero en uno de las puntas llaman a la FK _auto_ y en la otra _patente_

Si hacen eso van a terminar con una tabla Reserva que tiene ambas columnas "auto" y "patente". Excepto que como la relacion es inverse=true en Auto la columna "auto" va ser siempre null (patente va a tener el valor esperado).

El problemo es que cuando ustedes se traigan un auto de la base, hibernate va a usar la columna "patente" para joinear con todas sus Reservas. Esa columna nunca tiene nada => conclusion nunca les trae reservas.

**Comment by aitrusgit** [comment]
En el gist que subi sobre relacione bidireccionales hablaba justamente de la necesidad de ponerle el mismo nombre desde ambos lados: https://gist.github.com/aitrusgit/990d4f0081b730e8ce68

**Comment by aitrusgit** [comment]
Es mas, los tests que creé para el issue anterior no pasaban si esto no se corregía.

**Comment by alejandro11k** [comment]
Cambio en los mapeos
Reservas y Auto apuntan a la misma FK
