### ISSUE TITLE
Relacion Empresa->Categoria

### ISSUE THREAD

**Issue by aitrusgit** [alejandro11k/rentauto#9]
Viendo la tabla de Categoria me encuentro con esto:

```
mysql> describe categorias;
+--------+-------------+------+-----+---------+-------+
| Field  | Type        | Null | Key | Default | Extra |
+--------+-------------+------+-----+---------+-------+
| nombre | varchar(20) | NO   | PRI | NULL    |       |
| tipo   | varchar(1)  | NO   |     | NULL    |       |
| cuit   | varchar(20) | YES  | MUL | NULL    |       |
+--------+-------------+------+-----+---------+-------+
```

A que se debe el campo cuit. Suena a que una Categoria solo puede ser admitida en una Empresa... pero ese concepto esta mal.

Si vemos el modelo:

``` xtend
class Empresa {
    Set<Categoria> categoriasAdmitidas = newHashSet
```

Una `Empresa` tiene una lista de categorias admitidas, pero varias empresas podrian tener la misma categoria entre sus categorias admitidas (de hecho tiene sentido). Ese tipo de relacion **una Empresa tiene muchas Categorias, una Categoria puede ser contenida por mas de una empresa** debe ser modelada como una **many-to-many**. Ustedes en cambio usaron una one-to-many

**Comment by aitrusgit** [comment]
Suena a que se equivocaron y pusieron many-to-many en la relacion Empresa->Reserva (que no es una many-to-many) en lugar de Empresa->Categoria

![image](https://cloud.githubusercontent.com/assets/819334/10567765/414ec6e6-75e3-11e5-971f-90d4f4183705.png)

**Comment by alejandro11k** [comment]
cardinalidades corregidas en mapeo Empresa
